name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --quiet -r requirements-ci.txt
    - name: mypy
      run: |
        pip install --upgrade pip
        # pip install mypy --upgrade --quiet
        mypy megnet
    - name: flake8
      run: |
        # pip install flake8-black --upgrade --quiet
        flake8 --count --show-source --statistics megnet
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=20 --statistics megnet
    - name: pydocstyle
      run: |
        # pip install pydocstyle --upgrade --quiet
        pydocstyle --count megnet
    - name: pylint
      run: |
        # pip install pylint --upgrade --quiet
        pylint megnet
